runtime: python
env: flex
entrypoint: gunicorn -b :$PORT HangryBirds.wsgi
threadsafe: true

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static

- url: /(.*)
  static_files: static/(.*)
  upload: static/(.*)

env_variables:
  CLOUD_SQL_CONNECTION_NAME: hangrybirds:us-east1:poll-instance
  DB_USER: root
  DB_PASS: root
  DB_NAME: Restaurants

beta_settings:
  cloud_sql_instances: hangrybirds:us-east1:poll-instance