runtime: python
env: flex
entrypoint: gunicorn -b :$PORT HangryBirds.wsgi

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static

- url: /(.*)
  static_files: static/(.*)
  upload: static/(.*)
