# Generated by Django 3.0.2 on 2020-04-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTable',
            fields=[
                ('item_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('rest_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=100)),
                ('rest_loc', models.CharField(max_length=250)),
                ('rest_contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='ReviewTable',
            fields=[
                ('review_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('menuObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MenuTable')),
                ('userObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserTable')),
            ],
        ),
        migrations.AddField(
            model_name='menutable',
            name='restObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RestaurantTable'),
        ),
    ]
