# Generated by Django 3.0.2 on 2020-04-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200401_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtable',
            name='restObj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.RestaurantTable'),
            preserve_default=False,
        ),
    ]
