# Generated by Django 3.0.2 on 2020-04-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reviewtable_restobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewtable',
            name='review_ID',
        ),
        migrations.AddField(
            model_name='reviewtable',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
