# Generated by Django 3.0.2 on 2020-04-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200402_0539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewTable',
        ),
    ]
