# Generated by Django 3.0.2 on 2020-04-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_reviewtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('menuObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MenuTable')),
                ('restObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RestaurantTable')),
                ('userObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserTable')),
            ],
        ),
    ]
