# Generated by Django 3.0.2 on 2020-04-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reviewtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMenuTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('restObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RestaurantTable')),
                ('userObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserTable')),
            ],
        ),
    ]
