# Generated by Django 3.0.2 on 2020-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pendingmenutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='rest_img',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
